#! /bin/sh

bison --defines=dish.h dish.y; gcc -g -c xmacroplay.c; g++ -g -o dish Number.cpp StringFunctions.cpp spawn.cpp dish.tab.c xmacroplay.o -lX11 -lXtst
g++ -g -o sonic sonic.cpp StringFunctions.cpp
